# Pre-deploy script to inject API URL into frontend build
# This runs before Docker build, making the URL available at build time

$ErrorActionPreference = "Stop"

Write-Host "Preparing frontend environment for deployment..." -ForegroundColor Green

# Get the root directory (two levels up from the script)
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RootDir = Split-Path -Parent (Split-Path -Parent $ScriptDir)
$FrontendDir = Join-Path $RootDir "src/agentic-ui"
$EnvFile = Join-Path $FrontendDir ".env.production.local"

# Read environment variables from azd
$envValues = azd env get-values | Out-String
$envValues -split "`n" | ForEach-Object {
    if ($_ -match '^([^=]+)=(.*)$') {
        [Environment]::SetEnvironmentVariable($matches[1], $matches[2].Trim('"'))
    }
}

$ContainerEnvDomain = $env:AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN
$AgentApiUrl = ""

# If not set, try to construct from resource group info
if ([string]::IsNullOrEmpty($ContainerEnvDomain)) {
    $ApiFqdn = $env:AZURE_CONTAINER_APP_AGENTIC_API_FQDN
    
    if (-not [string]::IsNullOrEmpty($ApiFqdn)) {
        $AgentApiUrl = "https://$ApiFqdn"
    } else {
        $ResourceGroup = $env:AZURE_RESOURCE_GROUP
        if (-not [string]::IsNullOrEmpty($ResourceGroup)) {
            Write-Host "Fetching API Container App FQDN from Azure..." -ForegroundColor Cyan
            try {
                $ApiFqdn = az containerapp show `
                    --name agentic-api `
                    --resource-group $ResourceGroup `
                    --query "properties.configuration.ingress.fqdn" `
                    --output tsv 2>$null
                
                if (-not [string]::IsNullOrEmpty($ApiFqdn)) {
                    $AgentApiUrl = "https://$ApiFqdn"
                }
            } catch {
                # Ignore errors
            }
        }
    }
}

# If we still don't have the URL, use the known pattern from Bicep
if ([string]::IsNullOrEmpty($AgentApiUrl)) {
    $ResourceGroup = $env:AZURE_RESOURCE_GROUP
    if (-not [string]::IsNullOrEmpty($ResourceGroup)) {
        try {
            $DefaultDomain = az containerapp env list `
                --resource-group $ResourceGroup `
                --query "[0].properties.defaultDomain" `
                --output tsv 2>$null
            
            if (-not [string]::IsNullOrEmpty($DefaultDomain)) {
                $AgentApiUrl = "https://agentic-api.$DefaultDomain"
            }
        } catch {
            # Ignore errors
        }
    }
}

# Validate we have a URL
if ([string]::IsNullOrEmpty($AgentApiUrl)) {
    Write-Host "Warning: Could not determine AGENT_API_URL. Frontend will use runtime environment variable." -ForegroundColor Yellow
    Write-Host "The server-side proxy routes will still work with AGENT_API_URL set at container runtime." -ForegroundColor Yellow
    exit 0
}

# Write the environment file for the frontend build
Write-Host "Writing API URL to frontend environment file..." -ForegroundColor Cyan

$envContent = @"
# Auto-generated by predeploy script
# This file is used during the Next.js build process

# Server-side API URL (used by API routes/proxy)
AGENT_API_URL=$AgentApiUrl

# Client-side API URL (if needed for direct client calls)
# Uncomment if you want client-side code to call the API directly
# NEXT_PUBLIC_AGENT_API_URL=$AgentApiUrl
"@

Set-Content -Path $EnvFile -Value $envContent

Write-Host "Frontend environment configured successfully!" -ForegroundColor Green
Write-Host "  - AGENT_API_URL: $AgentApiUrl" -ForegroundColor Cyan
Write-Host "  - Environment file: $EnvFile" -ForegroundColor Cyan
